### PR TITLE
Add color detection for hex colors from Int values

### PR DESCRIPTION
**Pull request by dral3x**
Just another simple matcher for matching colors defines like this

```
UIColor(hex: 0x5856d6)
```

Of course, I can create this using this UIColor extention

```
extension UIColor {

    convenience init(red: Int, green: Int, blue: Int) {
        assert(red >= 0 && red <= 255, "Invalid red component")
        assert(green >= 0 && green <= 255, "Invalid green component")
        assert(blue >= 0 && blue <= 255, "Invalid blue component")

        self.init(red: CGFloat(red) / 255.0, green: CGFloat(green) / 255.0, blue: CGFloat(blue) / 255.0, alpha: 1.0)
    }

    convenience init(hex: Int) {
        self.init(red:(hex >> 16) & 0xff, green:(hex >> 8) & 0xff, blue:hex & 0xff)
    }
}
```

### CODE REVIEW

**Comment by onmyway133** [comment]
@dral3x Hi, thanks for the PR

I make `HexMatcher` a little special so that it does not check for `UIColor` or `NSColor`, because sometimes we have an array of strings of hex color codes.

But I think I will borrow from your code, and make the pattern accept `#FFAABB` as well as `0xFFAABB`

What do you think?

**Comment by dral3x** [comment]
Makes sense to me!

**Comment by onmyway133** [comment]
@dral3x So I made it here https://github.com/onmyway133/XcodeColorSense/commit/f8ca62f9e9715ce4d9ce86898cbd3b3394a2f7e0

It supports both styles

``` swift
let _ = NSColor.hex("#FFAABB")
let _ = UIColor(hex: 0xFFAABB)
```

I 'll close this PR for now. Feel free to reopen it. Many thanks. I like your PR

**Comment by dral3x** [comment]
Works great! 
Thank you for accepting my PR

**Pull request closed without merging**
